import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { loadKnowledgeHubPreferences, type KnowledgeHubPreferences } from "../data/knowledgeHub";

export type TranslationKey =
  | "nav.dashboard" | "nav.knowledge" | "nav.courses" | "nav.learn" | "nav.arena" | "nav.classes" | "nav.assessments" | "nav.certificates" | "nav.reports" | "nav.users"
  | "common.search" | "common.notifications" | "common.logout"
  | "personalize.title" | "personalize.description" | "personalize.setup" | "personalize.age" | "personalize.organisation" | "personalize.category" | "personalize.mode" | "personalize.goal"
  | "personalize.interest" | "personalize.favorite" | "personalize.style" | "personalize.challenge" | "personalize.course" | "personalize.notifications" | "personalize.language" | "personalize.font"
  | "personalize.appearance" | "personalize.save" | "personalize.saving" | "personalize.saved" | "personalize.preview";

const en: Record<TranslationKey, string> = {
  "nav.dashboard": "Dashboard", "nav.knowledge": "Personalize", "nav.courses": "Courses", "nav.learn": "Learn", "nav.arena": "Challenges", "nav.classes": "Classes", "nav.assessments": "Assessments", "nav.certificates": "Certificates", "nav.reports": "Reports", "nav.users": "Users",
  "common.search": "Search", "common.notifications": "Notifications", "common.logout": "Log out",
  "personalize.title": "Make learning fit you", "personalize.description": "Set your learning pathway, interests, pace, language, font, and appearance.", "personalize.setup": "Learning setup", "personalize.age": "Age band", "personalize.organisation": "School or organisation", "personalize.category": "Training category", "personalize.mode": "Learning mode", "personalize.goal": "Learning goal", "personalize.interest": "Interest category", "personalize.favorite": "Favourite interest", "personalize.style": "Learning style", "personalize.challenge": "Challenge preference", "personalize.course": "Course interest", "personalize.notifications": "Notifications", "personalize.language": "Language", "personalize.font": "App font", "personalize.appearance": "Appearance", "personalize.save": "Save preferences", "personalize.saving": "Saving", "personalize.saved": "Preferences applied", "personalize.preview": "Live preview",
};

const translations: Partial<Record<string, Partial<Record<TranslationKey, string>>>> = {
  Pidgin: { "nav.knowledge": "Arrange am", "nav.assessments": "Tests", "common.search": "Find something", "common.notifications": "Updates", "common.logout": "Comot", "personalize.title": "Make learning match you", "personalize.description": "Choose your learning plan, interest, language, font and app look.", "personalize.setup": "Your learning setup", "personalize.age": "Your age group", "personalize.organisation": "School or company", "personalize.category": "Training type", "personalize.mode": "How you wan learn", "personalize.goal": "Wetin you wan achieve", "personalize.interest": "Wetin you like", "personalize.favorite": "Your favourite", "personalize.style": "How you like learn", "personalize.challenge": "Challenge wey you like", "personalize.course": "Course wey interest you", "personalize.language": "Language", "personalize.font": "App writing", "personalize.appearance": "App look", "personalize.save": "Save am", "personalize.saving": "E dey save", "personalize.saved": "We don apply am", "personalize.preview": "See how e go look" },
  French: { "nav.dashboard": "Tableau de bord", "nav.knowledge": "Personnaliser", "nav.courses": "Cours", "nav.learn": "Apprendre", "nav.arena": "Défis", "nav.classes": "Classes", "nav.assessments": "Évaluations", "nav.certificates": "Certificats", "nav.reports": "Rapports", "nav.users": "Utilisateurs", "common.search": "Rechercher", "common.notifications": "Notifications", "common.logout": "Déconnexion", "personalize.title": "Adaptez l’apprentissage à vos besoins", "personalize.description": "Choisissez votre parcours, vos intérêts, votre langue, votre police et votre apparence.", "personalize.setup": "Configuration", "personalize.age": "Tranche d’âge", "personalize.organisation": "École ou organisation", "personalize.category": "Catégorie de formation", "personalize.mode": "Mode d’apprentissage", "personalize.goal": "Objectif", "personalize.interest": "Catégorie d’intérêt", "personalize.favorite": "Intérêt favori", "personalize.style": "Style d’apprentissage", "personalize.challenge": "Défi préféré", "personalize.course": "Cours préféré", "personalize.language": "Langue", "personalize.font": "Police", "personalize.appearance": "Apparence", "personalize.save": "Enregistrer", "personalize.saving": "Enregistrement", "personalize.saved": "Préférences appliquées", "personalize.preview": "Aperçu" },
  Yoruba: { "nav.dashboard": "Ojú-iṣẹ́", "nav.knowledge": "Ṣe àdáni", "nav.courses": "Àwọn ẹ̀kọ́", "nav.learn": "Kọ́ ẹ̀kọ́", "nav.arena": "Ìpèníjà", "nav.classes": "Kíláàsì", "nav.assessments": "Ìdánwò", "nav.certificates": "Ìwé-ẹ̀rí", "nav.reports": "Àwọn ìròyìn", "nav.users": "Àwọn olumulo", "common.search": "Ṣàwárí", "common.notifications": "Ìfitónilétí", "common.logout": "Jáde", "personalize.title": "Mú ẹ̀kọ́ bá ọ mu", "personalize.description": "Ṣètò ọ̀nà ẹ̀kọ́, ohun tí o fẹ́ràn, ìyára, èdè, fọ́ǹtì àti ìrísí.", "personalize.setup": "Ètò ẹ̀kọ́", "personalize.age": "Ẹgbẹ́ ọjọ́-orí", "personalize.organisation": "Ilé-ẹ̀kọ́ tàbí àjọ", "personalize.category": "Ẹ̀ka ìdánilẹ́kọ̀ọ́", "personalize.mode": "Ọ̀nà ẹ̀kọ́", "personalize.goal": "Àfojúsùn ẹ̀kọ́", "personalize.interest": "Ẹ̀ka ìfẹ́", "personalize.favorite": "Ìfẹ́ ààyò", "personalize.style": "Àṣà ẹ̀kọ́", "personalize.challenge": "Ìpèníjà ààyò", "personalize.course": "Ẹ̀kọ́ tí o fẹ́", "personalize.notifications": "Ìfitónilétí", "personalize.language": "Èdè", "personalize.font": "Fọ́ǹtì app", "personalize.appearance": "Ìrísí", "personalize.save": "Fi àwọn ààyò pamọ́", "personalize.saving": "Ń fipamọ́", "personalize.saved": "A ti lo àwọn ààyò", "personalize.preview": "Àwòrán lẹ́sẹ̀kẹsẹ̀" },
  Hausa: { "nav.dashboard": "Allon sarrafawa", "nav.knowledge": "Keɓance", "nav.courses": "Darussa", "nav.learn": "Koyo", "nav.arena": "Kalubale", "nav.classes": "Azuzuwa", "nav.assessments": "Jarabawa", "nav.certificates": "Takaddun shaida", "nav.reports": "Rahotanni", "nav.users": "Masu amfani", "common.search": "Bincika", "common.notifications": "Sanarwa", "common.logout": "Fita", "personalize.title": "Daidaita koyo da kai", "personalize.description": "Saita hanyar koyo, abubuwan sha’awa, sauri, harshe, rubutu da bayyanar app.", "personalize.setup": "Tsarin koyo", "personalize.age": "Rukunin shekaru", "personalize.organisation": "Makaranta ko ƙungiya", "personalize.category": "Rukunin horo", "personalize.mode": "Hanyar koyo", "personalize.goal": "Burin koyo", "personalize.interest": "Rukunin sha’awa", "personalize.favorite": "Abin da aka fi so", "personalize.style": "Salon koyo", "personalize.challenge": "Kalubalen da aka fi so", "personalize.course": "Darasin da ake so", "personalize.notifications": "Sanarwa", "personalize.language": "Harshe", "personalize.font": "Salon rubutu", "personalize.appearance": "Bayyanar app", "personalize.save": "Ajiye zaɓuɓɓuka", "personalize.saving": "Ana ajiyewa", "personalize.saved": "An yi amfani da zaɓuɓɓuka", "personalize.preview": "Dubawa kai tsaye" },
  Igbo: { "nav.dashboard": "Ogwe njikwa", "nav.knowledge": "Hazie nke gị", "nav.courses": "Ihe ọmụmụ", "nav.learn": "Mụta", "nav.arena": "Ihe ịma aka", "nav.classes": "Klas", "nav.assessments": "Nnwale", "nav.certificates": "Asambodo", "nav.reports": "Akụkọ", "nav.users": "Ndị ọrụ", "common.search": "Chọọ", "common.notifications": "Ọkwa", "common.logout": "Pụọ", "personalize.title": "Mee ka ọmụmụ dabaara gị", "personalize.description": "Hazie ụzọ ọmụmụ, mmasị, ọsọ, asụsụ, mkpụrụedemede na ọdịdị app.", "personalize.setup": "Nhazi ọmụmụ", "personalize.age": "Otu afọ", "personalize.organisation": "Ụlọ akwụkwọ ma ọ bụ nzukọ", "personalize.category": "Ụdị ọzụzụ", "personalize.mode": "Ụzọ ọmụmụ", "personalize.goal": "Ebumnuche ọmụmụ", "personalize.interest": "Ụdị mmasị", "personalize.favorite": "Mmasị kachasị", "personalize.style": "Ụzọ ịmụ ihe", "personalize.challenge": "Ihe ịma aka kachasị", "personalize.course": "Ihe ọmụmụ masịrị gị", "personalize.notifications": "Ọkwa", "personalize.language": "Asụsụ", "personalize.font": "Ụdị mkpụrụedemede", "personalize.appearance": "Ọdịdị app", "personalize.save": "Chekwaa nhọrọ", "personalize.saving": "Na-echekwa", "personalize.saved": "Etinyela nhọrọ", "personalize.preview": "Nlele ozugbo" },
};

const interfacePhrases: Record<string, Record<string, string>> = {
  Yoruba: { "Question Library": "Ibi ìpamọ́ ìbéèrè", "Create question": "Ṣẹ̀dá ìbéèrè", "New bank": "Ibi ìpamọ́ tuntun", "Upload": "Gbé sókè", "CSV template": "Àpẹẹrẹ CSV", "JSON template": "Àpẹẹrẹ JSON", "All types": "Gbogbo irú", "All difficulties": "Gbogbo ìṣòro", "All subjects": "Gbogbo kókó", "All courses": "Gbogbo ẹ̀kọ́", "All lessons": "Gbogbo ẹ̀kọ́ kékeré", "All tags": "Gbogbo àmì", "Clear": "Pa rẹ́", "Select random": "Yan láìlérò", "Add to assessment": "Fi kún ìdánwò", "Edit question": "Ṣàtúnṣe ìbéèrè", "Duplicate question": "Ṣe ẹ̀dà ìbéèrè", "Delete question": "Pa ìbéèrè", "Save changes": "Fi àyípadà pamọ́", "Save to library": "Fi pamọ́ sí ibi ìpamọ́", "Cancel": "Fagilé", "Continue": "Tẹ̀síwájú", "Back": "Padà", "Loading page...": "Ń gbé ojúewé wọlé...", "Profile": "Àkọsílẹ̀", "My learning": "Ẹ̀kọ́ mi", "Course": "Ẹ̀kọ́", "Lesson": "Ẹ̀kọ́ kékeré", "Subject": "Kókó", "Difficulty": "Ìṣòro", "Points": "Àwọn àmì", "Easy": "Rọrùn", "Medium": "Àárín", "Hard": "Líle" },
  Hausa: { "Question Library": "Ma’ajiyar tambayoyi", "Create question": "Ƙirƙiri tambaya", "New bank": "Sabuwar ma’ajiya", "Upload": "Loda", "CSV template": "Samfurin CSV", "JSON template": "Samfurin JSON", "All types": "Duk nau’ikan", "All difficulties": "Duk matakan wahala", "All subjects": "Duk batutuwa", "All courses": "Duk darussa", "All lessons": "Duk darussa", "All tags": "Duk alamomi", "Clear": "Share", "Select random": "Zaɓi bazuwar", "Add to assessment": "Ƙara zuwa jarabawa", "Edit question": "Gyara tambaya", "Duplicate question": "Kwafi tambaya", "Delete question": "Goge tambaya", "Save changes": "Ajiye canje-canje", "Save to library": "Ajiye a ma’ajiya", "Cancel": "Soke", "Continue": "Ci gaba", "Back": "Koma", "Loading page...": "Ana loda shafi...", "Profile": "Bayanan martaba", "My learning": "Koyona", "Course": "Darasi", "Lesson": "Darasi", "Subject": "Batu", "Difficulty": "Wahala", "Points": "Maki", "Easy": "Mai sauƙi", "Medium": "Matsakaici", "Hard": "Mai wuya" },
  Igbo: { "Question Library": "Ọba ajụjụ", "Create question": "Mepụta ajụjụ", "New bank": "Ọba ọhụrụ", "Upload": "Bulite", "CSV template": "Nlereanya CSV", "JSON template": "Nlereanya JSON", "All types": "Ụdị niile", "All difficulties": "Ọkwa isi ike niile", "All subjects": "Isiokwu niile", "All courses": "Ihe ọmụmụ niile", "All lessons": "Nkuzi niile", "All tags": "Akara niile", "Clear": "Hichapụ", "Select random": "Họrọ na-enweghị usoro", "Add to assessment": "Tinye na nnwale", "Edit question": "Dezie ajụjụ", "Duplicate question": "Detuo ajụjụ", "Delete question": "Hichapụ ajụjụ", "Save changes": "Chekwaa mgbanwe", "Save to library": "Chekwaa n’ọba", "Cancel": "Kagbuo", "Continue": "Gaa n’ihu", "Back": "Laghachi", "Loading page...": "Na-ebunye peeji...", "Profile": "Profaịlụ", "My learning": "Ọmụmụ m", "Course": "Ihe ọmụmụ", "Lesson": "Nkuzi", "Subject": "Isiokwu", "Difficulty": "Isi ike", "Points": "Akara", "Easy": "Dị mfe", "Medium": "Etiti", "Hard": "Siri ike" },
};

type LocalizationValue = { language: string; t: (key: TranslationKey, fallback?: string) => string };
const LocalizationContext = createContext<LocalizationValue | null>(null);
const textOriginals = new WeakMap<Text, string>();
const attributeOriginals = new WeakMap<Element, Map<string, string>>();

function InterfaceTranslator({ language }: { language: string }) {
  useEffect(() => {
    const dictionary = interfacePhrases[language] ?? {};
    const translate = (root: ParentNode) => {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); let node = walker.nextNode();
      while (node) { const textNode = node as Text; const parent = textNode.parentElement; if (parent && !parent.closest("[data-no-translate]") && !["SCRIPT", "STYLE", "TEXTAREA"].includes(parent.tagName)) { const original = textOriginals.get(textNode) ?? textNode.nodeValue ?? ""; textOriginals.set(textNode, original); const trimmed = original.trim(); const translated = dictionary[trimmed] ?? trimmed; textNode.nodeValue = original.replace(trimmed, translated); } node = walker.nextNode(); }
      const elements = root instanceof Element ? [root, ...Array.from(root.querySelectorAll("[placeholder],[title],[aria-label]"))] : Array.from(root.querySelectorAll("[placeholder],[title],[aria-label]"));
      elements.forEach((element) => ["placeholder", "title", "aria-label"].forEach((attribute) => { const current = element.getAttribute(attribute); if (!current) return; const originals = attributeOriginals.get(element) ?? new Map<string, string>(); if (!attributeOriginals.has(element)) attributeOriginals.set(element, originals); const original = originals.get(attribute) ?? current; originals.set(attribute, original); element.setAttribute(attribute, dictionary[original] ?? original); }));
    };
    translate(document.body); const observer = new MutationObserver((records) => records.forEach((record) => record.addedNodes.forEach((node) => { if (node instanceof Element) translate(node); else if (node.parentElement) translate(node.parentElement); })));
    observer.observe(document.body, { childList: true, subtree: true }); return () => observer.disconnect();
  }, [language]);
  return null;
}

export function LocalizationProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState(() => loadKnowledgeHubPreferences().languagePreference);
  useEffect(() => { const handler = (event: Event) => { const detail = (event as CustomEvent<KnowledgeHubPreferences>).detail; setLanguage(detail?.languagePreference || loadKnowledgeHubPreferences().languagePreference); }; window.addEventListener("knowledge-hub:preferences-updated", handler); return () => window.removeEventListener("knowledge-hub:preferences-updated", handler); }, []);
  const value = useMemo<LocalizationValue>(() => ({ language, t: (key, fallback) => translations[language]?.[key] || en[key] || fallback || key }), [language]);
  return <LocalizationContext.Provider value={value}><InterfaceTranslator language={language} />{children}</LocalizationContext.Provider>;
}

export function useLocalization() { const context = useContext(LocalizationContext); if (!context) throw new Error("useLocalization must be used within LocalizationProvider."); return context; }
